<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password</name>
   <tag></tag>
   <elementGuidId>2b465b37-07b2-432f-a48f-e240be8adfba</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>placeholder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: hintText, css: hintCss</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i0281&quot;)/div[@class=&quot;outer&quot;]/div[@class=&quot;middle&quot;]/div[@class=&quot;inner fade-in-lightbox&quot;]/div[3]/div[1]/div[@class=&quot;pagination-view animate has-identity-banner slide-in-next&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-md-24&quot;]/div[@class=&quot;placeholderContainer&quot;]/div[@class=&quot;placeholderInnerContainer&quot;]/div[@class=&quot;placeholder&quot;]</value>
   </webElementProperties>
</WebElementEntity>
